#define TRUE 1
#define FALSE 0
#define ERROR -1
#define NUM_OF_OPERATIONS 16
#define NUM_OF_REGISTERS 8
#define MAX_OPERAND_TYPES 4
#define MAX_OPERANDS 2
#define MAX_LINE 81
#define PRE_MACRO_EXT ".as"
#define POST_MACRO_EXT ".am"
#define OB_EXT ".ob"
#define ENT_EXT ".ent"
#define EXT_EXT ".ext"
#define BASE_10 10
#define MAX_CODE_LINES 300
#define MAX_DATA_LINES 300
#define OPCODE_OFFSET 18
#define FUNCT_OFFSET 3
#define DEST_REG_OFFSET 8
#define SRC_REG_OFFSET 13
#define ADD_MTD_SRC_OFFSET 16
#define ADD_MTD_DEST_OFFSET 11
#define ARE_OFFSET 3
#define A_OFFSET 2
#define R_OFFSET 1
#define E_OFFSET 0
#define BITS_MASK 16777215;
