
typedef enum
{
    SUCCESS,
    ERROR_MEMORY_ALLOCATION_FAILED,
    ERROR_FILE_NOT_FOUND,
    ERROR_FILE_OPEN_FAILED,
    ERROR_FILE_CLOSE_FAILED,
    ERROR_LINE_TOO_LONG,
    ERROR_MACRO_NAME_MISSING,
    ERROR_ONLY_SOURCE_OPERAND,
    ERROR_ONLY_TARGET_OPERAND,
    ERROR_INVALID_OPERAND_TYPE,
    ERROR_INVALID_OPERAND_COUNT,
    ERROR_INVALID_LABEL_NAME_MACRO,
    ERROR_INVALID_LABEL_NAME_REGISTER,
    ERROR_INVALID_LABEL_NAME_OPERATION,
    ERROR_INVALID_LABEL_NAME_DIRECTIVE,
} ErrorCode;